name: run-javaVersion
on:
  workflow_dispatch:
    inputs:
      logLevels:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  testVersionJava:
    runs-on: poc-runner-2
    steps:
      - name: verificacionVersionJava
        run: |
          java -version
